const container = document.querySelector(".container");
const pRed = document.createElement("p");
pRed.style.color = "red";
pRed.textContent = "Hey I'm red";
container.appendChild(pRed);
const hBlue = document.createElement("h3");
hBlue.style.color = "blue";
hBlue.textContent = "Hey I'm Blue";
container.append(hBlue);
const childDiv = document.createElement("div");
childDiv.style.backgroundColor = "pink";
childDiv.style.border = "1px solid black";
const hDiv = document.createElement("h1");
const pDiv = document.createElement("p");
hDiv.textContent = "Hey I'm in a DIV";
pDiv.textContent = "ME TOO";
childDiv.appendChild(hDiv);
childDiv.appendChild(pDiv);
container.appendChild(childDiv);